### PR TITLE
Fix build steps.

### PR DESCRIPTION
**Pull request by danharvey**
I think this used to be a Makefile, but now uses Python's setup library.

### CODE REVIEW

**Comment by danharvey** [comment]
@larsblumberg great! @IanHarvey could we get this PR merged?

**Comment by larsblumberg** [comment]
Can we then get rid of [bluepy/Makefile](https://github.com/IanHarvey/bluepy/blob/master/bluepy/Makefile)?

**Comment by danharvey** [comment]
Thanks

**Comment by IanHarvey** [comment]
So **setup.py** still isn't actually working. I tried to make a package to submit to Pypi, but the build process (**python setup.py sdist**) isn't including any C source files in the archive.

**Comment by Shiselster** [comment]
what's wrong with **python setup.py install** ? It works fine for me..

**Comment by larsblumberg** [comment]
@Shiselster On a freshly installed Raspbian running this command gave me:

`make: *** No targets specified and no makefile found. Stop.`

Any ideas why I got this? This PR fixed it for me.

**Comment by IanHarvey** [comment]
'install' should basically do the right thing, it's using the **sdist** command (to build a source distribution for uploading to pypi) isn't fixed yet. It's not including any C files (or the Makefile) for the **bluepy-helper** build. Setuptools has a way of building extensions (https://docs.python.org/2/extending/building.html) but it's not exactly what we need (it produces a .so, not an executable).

**Comment by larsblumberg** [comment]
@IanHarvey Thanks for clarifying and for your work on blueply

**Comment by IanHarvey** [comment]
I've now got a testable version uploaded to PyPI - see https://pypi.python.org/pypi/bluepy/1.0.2

You should be able to install this with **sudo pip install bluepy** - note I've only tested it on Ubuntu so far, it may have teething troubles with e.g. Raspbian.

**Pull request merged**
