### PR TITLE
Add passive scan capabilities

### PR DESCRIPTION
**Pull request by gandy92**
- Add commands `pasv` and `pasvend` to bluepy-helper using HCI to listen for `ADV_IND` packages only
- Add option `passive` to Scanner class, switching between `scan`/`scanend` and `pasv`/`pasvend`
- Add example script `scanner.py`

### CODE REVIEW

**Comment by Snevzor** [comment]
Great work!

This would also be better suited for fast active scanning with duplicates...

**Comment by IanHarvey** [comment]
Thanks for the contribution  - that's now pulled onto `master`.  I've not tested it yet but it looks like it won't affect anything else, so I'll make sure it's OK before the next release.

Thanks again,
Ian

**Comment by gandy92** [comment]
Thank you for accepting the pull request. Meanwhile, I did find something I do not quite know how to fix. When terminating a python script during a passive scan with Crtl+c, the helper is terminated but the passive scanning keeps being enabled. Starting the script again may lead to unexpected results because some ble parameters may not be changes while scanning is enabled. I would rather not introduce a fixed time limit to passive scanning to avoid unnecessary dead-time. Do you see an elegant and robust solution to this?

**Comment by jan-xyz** [comment]
`Ctrl+C` throws a KeyboardInterrupt Exception, maybe you can catch that and do the clean up before killing the script?

**Comment by nitrag** [comment]
My interpretation of passive scan is that it is asynchronous. Is this not the case?

In the following example the timer doesn't start until after the 15 second scan.
```python
scanner.scan(15.0, passive=True)

i=0
while i < 15:
    i += 1
    print(""+str(i))
    sleep(1)
```

**Comment by gandy92** [comment]
Passive scanning refers to the bluetooth stack just listening to advertising frames (ADV_IND) while during active scan it would request additional ADV_RSP frames for each received ADV_IND. Maybe what you want to do is call scan() in its own thread.

**Pull request merged**
