### PR TITLE
Added Thingy:52 support.

### PR DESCRIPTION
**Pull request by gamnes**
Added support for Nordic Semiconductor ASA IoT Sensor Kit, Thingy:52. Example shows how interface can be used to send/read/get notified by data from the Thingy:52.

See https://www.nordicsemi.com/eng/Products/Nordic-Thingy-52 for more information. If its desirable to test before merge (i have tested both Python2 and 3 on the Raspberry Pi) let me know and i could get one module shipped to you so that you can test it and verify that its working/suggest any changes.

### CODE REVIEW

**Comment by N00BMmika** [comment]
Hi @gamnes, it was glad to find Thingy support in bluepy. 

In my Rpi3 I can see Thingy with this command:
```
hcitool lescan
C4:A3:F9:FD:C6:EF Thingy
```
Sometimes i have been able to get Thingy connected with followin code
```
from bluepy import btle, thingy52
mac_address="C4:A3:F9:FD:C6:EF"
thingy = thingy52.Thingy52(mac_address)
```
but usually I get following kind of error message:
`bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral C4:A3:F9:FD:C6:EF, addr type: random`

I can connect to Thingy always with Thingy Android app.
Do you have any suggestion how to get Thingy working reliably with bluepy?

Thanks,
Mika

**Comment by N00BMmika** [comment]
Hi @gamnes, seems that it's RPI3 problem (or Thingy52 problem). Not problem of this library. I was able to reproduce same connectivity problem with gatttool.

**Comment by gamnes** [comment]
Hi @N00BMmika, I'm pretty sure I was testing with a Raspberry Pi 3 along with the Thingy:52 when I did my Alexa demo earlier this year: https://www.youtube.com/watch?v=cUfVo0auOUk&t=41s. Here is my blog post for that https://github.com/gamnes/alexa-nordic-thingy. 

This devzone post explains my set up of that RPi: https://devzone.nordicsemi.com/blogs/1160/walkthrough-of-nordic-thingy52-nodejs-raspberry-pi/. 


Maybe this is related to the OS you are running on the RPi? 
Did you update all the libraries, etc? 

There is a comment here mentioning some kworker issue, maybe thats related to what you are seeing? https://devzone.nordicsemi.com/b/blog/posts/nordic-thingy52-nodejsraspberry-pi-demos.

**Comment by N00BMmika** [comment]
Hi @gamnes, Thanks for quick reply.
I have done `sudo apt-get update` and `sudo apt-get upgrade` to my Raspbian GNU/Linux 9 (stretch) 

 I did reset bluetooth adapter 
`sudo hciconfig hci0 reset`
according to instructions at here http://raspberry-projects.com/pi/pi-operating-systems/raspbian/bluetooth/bluetooth-commands 
I think it helped. I suppose 
`sudo reboot` may not reset bluetooth.

As you wrote in https://devzone.nordicsemi.com/b/blog/posts/walkthrough-of-nordic-thingy52-nodejs-raspberry-pi, you have found "BLE Issues on the RPi".

Anyhow, bluepy.Thingy52 seems to work now quite reliably. Still have problems to get connection with Homeassistant https://github.com/chriswils/thingy52_homeassistant but that's another story.

Regards,
Mika

**Comment by gamnes** [comment]
Yes, I did have BLE issues on the Pi - it seems like a reboot was required after several connects/disconnects, but I never had the time to look into it.

Good that it seems to work reliably now:) I've never looked at Homeassistant before, so I won't be able to help you out there I'm afraid:/ - But if you have any more issues with the Thingy just let me know and maybe I can help you out.

**Pull request merged**
